Our First "Deep" Neural Network

In [17]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

alpha = 0.2
hidden_size = 4

streetlights = np.array( [[ 1, 0, 1 ], [ 0, 1, 1 ], [ 0, 0, 1 ], [ 1, 1, 1 ]] ) 
walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

layer_0 = streetlights[0]
print("layer_0 shape: " + str(layer_0.shape))

layer_1 = relu(np.dot(layer_0,weights_0_1)) 
print("weights_0_1 shape: " + str(weights_0_1.shape) + "\n")
print("layer_1 shape: " + str(layer_1.shape))

layer_2 = np.dot(layer_1,weights_1_2)
print("weights_1_2 shape: " + str(weights_1_2.shape) + "\n")
print("layer_2 shape: " + str(layer_2.shape))

print(layer_2)

layer_0 shape: (3,)
weights_0_1 shape: (3, 4)

layer_1 shape: (4,)
weights_1_2 shape: (4, 1)

layer_2 shape: (1,)
[ 0.39194327]


In [14]:
print(layer_0)
print(weights_0_1)

[1 0 1]
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]


In [18]:
print(layer_1)
print(weights_1_2)

[-0.          0.51828245 -0.         -0.        ]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
